version: '3.4'

volumes:
  mysql_data:

services:
  mysql:
    image: library/mysql:8.0.21
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=transactional_mail
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 8021:3306
  app:
    build:
      dockerfile: Dockerfile
      target: dependencies
      context: ./
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    env_file:
      - ./.env.local
    volumes:
      - ./:/opt/application
      - /opt/application/vendor
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transactional.rule=Host(`localhost`)"
      - "traefik.http.routers.transactional.entrypoints=web"
  rabbitmq:
    image: rabbitmq:management
    volumes:
      - ./:/opt/application
    ports:
      - 5672:5672
      - 15672:15672
  traefik:
    image: "traefik:v2.6"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8020:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"